# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.grpc import service1_pb2 as app_dot_grpc_dot_service1__pb2


class Service1Stub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessName = channel.unary_unary(
                '/app.grpc.Service1/ProcessName',
                request_serializer=app_dot_grpc_dot_service1__pb2.ProcessNameRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_service1__pb2.ProcessNameResponse.FromString,
                )


class Service1Servicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Service1Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessName': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessName,
                    request_deserializer=app_dot_grpc_dot_service1__pb2.ProcessNameRequest.FromString,
                    response_serializer=app_dot_grpc_dot_service1__pb2.ProcessNameResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'app.grpc.Service1', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Service1(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/app.grpc.Service1/ProcessName',
            app_dot_grpc_dot_service1__pb2.ProcessNameRequest.SerializeToString,
            app_dot_grpc_dot_service1__pb2.ProcessNameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
