# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/grpc/service1.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='app/grpc/service1.proto',
  package='app.grpc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17\x61pp/grpc/service1.proto\x12\x08\x61pp.grpc\"\"\n\x12ProcessNameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"#\n\x13ProcessNameResponse\x12\x0c\n\x04name\x18\x01 \x01(\t2X\n\x08Service1\x12L\n\x0bProcessName\x12\x1c.app.grpc.ProcessNameRequest\x1a\x1d.app.grpc.ProcessNameResponse\"\x00\x62\x06proto3'
)




_PROCESSNAMEREQUEST = _descriptor.Descriptor(
  name='ProcessNameRequest',
  full_name='app.grpc.ProcessNameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='app.grpc.ProcessNameRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=71,
)


_PROCESSNAMERESPONSE = _descriptor.Descriptor(
  name='ProcessNameResponse',
  full_name='app.grpc.ProcessNameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='app.grpc.ProcessNameResponse.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=108,
)

DESCRIPTOR.message_types_by_name['ProcessNameRequest'] = _PROCESSNAMEREQUEST
DESCRIPTOR.message_types_by_name['ProcessNameResponse'] = _PROCESSNAMERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProcessNameRequest = _reflection.GeneratedProtocolMessageType('ProcessNameRequest', (_message.Message,), {
  'DESCRIPTOR' : _PROCESSNAMEREQUEST,
  '__module__' : 'app.grpc.service1_pb2'
  # @@protoc_insertion_point(class_scope:app.grpc.ProcessNameRequest)
  })
_sym_db.RegisterMessage(ProcessNameRequest)

ProcessNameResponse = _reflection.GeneratedProtocolMessageType('ProcessNameResponse', (_message.Message,), {
  'DESCRIPTOR' : _PROCESSNAMERESPONSE,
  '__module__' : 'app.grpc.service1_pb2'
  # @@protoc_insertion_point(class_scope:app.grpc.ProcessNameResponse)
  })
_sym_db.RegisterMessage(ProcessNameResponse)



_SERVICE1 = _descriptor.ServiceDescriptor(
  name='Service1',
  full_name='app.grpc.Service1',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=110,
  serialized_end=198,
  methods=[
  _descriptor.MethodDescriptor(
    name='ProcessName',
    full_name='app.grpc.Service1.ProcessName',
    index=0,
    containing_service=None,
    input_type=_PROCESSNAMEREQUEST,
    output_type=_PROCESSNAMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVICE1)

DESCRIPTOR.services_by_name['Service1'] = _SERVICE1

# @@protoc_insertion_point(module_scope)
